spring.application.name=order-processing-system
spring.config.import=optional:file:./.env[.properties]

spring.datasource.url=${ORDER_DB_URL:jdbc:postgresql://localhost:5432/order_processing}
spring.datasource.username=${ORDER_DB_USERNAME:order_app}
spring.datasource.password=${ORDER_DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
server.error.include-message=never
